return {
 ["LinuxLibertineO/B:mode=base;script=latn;language=dflt;#b#655361"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_RB.otf", false },
 ["LinuxLibertineO/B:mode=base;script=latn;language=dflt;#b#655362"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_RB.otf", false },
 ["LinuxLibertineO/BI:mode=base;script=latn;language=dflt;#bi#655361"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_RBI.otf", false },
 ["LinuxLibertineO/BI:mode=base;script=latn;language=dflt;#bi#655362"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_RBI.otf", false },
 ["LinuxLibertineO/I:mode=base;script=latn;language=dflt;#i#655361"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_RI.otf", false },
 ["LinuxLibertineO/I:mode=base;script=latn;language=dflt;#i#655362"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_RI.otf", false },
 ["LinuxLibertineO/I:mode=base;script=latn;language=dflt;+tlig;#i#395046"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_RI.otf", false },
 ["LinuxLibertineO/I:mode=base;script=latn;language=dflt;+tlig;#i#526728"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_RI.otf", false },
 ["LinuxLibertineO/I:mode=base;script=latn;language=dflt;+tlig;#i#658410"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_RI.otf", false },
 ["LinuxLibertineO:mode=base;#655358"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_R.otf", false },
 ["LinuxLibertineO:mode=base;#655362"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_R.otf", false },
 ["LinuxLibertineO:mode=base;script=latn;language=dflt;#655361"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_R.otf", false },
 ["LinuxLibertineO:mode=base;script=latn;language=dflt;#655362"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_R.otf", false },
 ["LinuxLibertineO:mode=base;script=latn;language=dflt;+tlig;#395046"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_R.otf", false },
 ["LinuxLibertineO:mode=base;script=latn;language=dflt;+tlig;#526728"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_R.otf", false },
 ["LinuxLibertineO:mode=base;script=latn;language=dflt;+tlig;#658410"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/libertine/LinLibertine_R.otf", false },
 ["LinuxLibertineOBold/B:mode=base;script=latn;language=dflt;#b#655361"]={ "/usr/share/fonts/opentype/linux-libertine/LinLibertine_RB.otf", false },
 ["LinuxLibertineOBold/BI:mode=base;script=latn;language=dflt;#bi#655361"]={ "/usr/share/fonts/opentype/linux-libertine/LinLibertine_RB.otf", false },
 ["LinuxLibertineOBold/I:mode=base;script=latn;language=dflt;#i#655361"]={ "/usr/share/fonts/opentype/linux-libertine/LinLibertine_RB.otf", false },
 ["LinuxLibertineOBold:mode=base;#655358"]={ "/usr/share/fonts/opentype/linux-libertine/LinLibertine_RB.otf", false },
 ["LinuxLibertineOBold:mode=base;#655362"]={ "/usr/share/fonts/opentype/linux-libertine/LinLibertine_RB.otf", false },
 ["LinuxLibertineOBold:mode=base;script=latn;language=dflt;#655361"]={ "/usr/share/fonts/opentype/linux-libertine/LinLibertine_RB.otf", false },
 ["LinuxLibertineOBold:mode=base;script=latn;language=dflt;#655362"]={ "/usr/share/fonts/opentype/linux-libertine/LinLibertine_RB.otf", false },
}
